// <auto-generated />
using EmpresaWebApi.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace EmpresaWebApi.Migrations
{
    [DbContext(typeof(EmpresaContext))]
    [Migration("20190322152550_02_Add_ApellidoMaterno_Empleado")]
    partial class _02_Add_ApellidoMaterno_Empleado
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EmpresaWebApi.Models.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Descripcion")
                        .IsRequired();

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("EmpresaWebApi.Models.Empleado", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<int>("IdDepartamento");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("EmpresaWebApi.Models.Empleado", b =>
                {
                    b.HasOne("EmpresaWebApi.Models.Departamento", "FK_DepartamentoEmpleado")
                        .WithMany("Empleados")
                        .HasForeignKey("IdDepartamento")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
